# Generated by Django 4.1 on 2022-08-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracao', models.DurationField()),
                ('data_de_lancamento', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Filme', to='core.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Artista', to='core.filme')),
            ],
        ),
    ]
