# Generated by Django 4.1 on 2022-08-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='personagem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
